### ISSUE TITLE
Error on latest version lacking zeronsd release packages

### ISSUE THREAD

**Issue by gabrielribbae** [daoudeddy/hassio-addons#15]
Hi there! thank you for effort in adding this project into homeassistant :)

**Describe the bug**
Add On is not installing on latest version.

**To Reproduce**
1. Add repository https://github.com/daoudeddy/hassio-addons
2. Click on Install Add-On Button
3. See error

**Expected behavior**
Container image downloaded and ready to be configured.

**Additional context**

It seems related due to Dockerfile script requiring the arch-specific release package in latest versions.

**Logs**

22-05-31 07:43:09 INFO (SyncWorker_1) [supervisor.docker.addon] Starting build for 4a07b2b6/armv7-addon-zerons:20220529
22-05-31 07:43:14 ERROR (SyncWorker_1) [supervisor.docker.addon] Can't build 4a07b2b6/armv7-addon-zerons:20220529: The command '/bin/ash -o pipefail -c wget "https://github.com/daoudeddy/zerons-addon/releases/latest/download/zeronsd-${BUILD_ARCH}.tar.gz" -O zeronsd.tar.gz' returned a non-zero code: 8
22-05-31 07:43:14 ERROR (SyncWorker_1) [supervisor.docker.addon] Build log: 
Step 1/14 : ARG BUILD_FROM
Step 2/14 : FROM $BUILD_FROM
 ---> 0b6dcc4e767c
Step 3/14 : ARG BUILD_ARCH
 ---> Using cache
 ---> 740c6a1c82a4
Step 4/14 : RUN apk add wget tar openssl ca-certificates
 ---> Using cache
 ---> d790685f0154
Step 5/14 : RUN wget "https://github.com/daoudeddy/zerons-addon/releases/latest/download/zeronsd-${BUILD_ARCH}.tar.gz" -O zeronsd.tar.gz
 ---> Running in ff014a637327
--2022-05-31 11:43:12--  https://github.com/daoudeddy/zerons-addon/releases/latest/download/zeronsd-armv7.tar.gz

Resolving github.com (github.com)... 
20.201.28.151
Connecting to github.com (github.com)|20.201.28.151|:443... 
connected.

HTTP request sent, awaiting response... 
301 Moved Permanently
Location: https://github.com/daoudeddy/hassio-addons/releases/latest/download/zeronsd-armv7.tar.gz [following]

--2022-05-31 11:43:13--  https://github.com/daoudeddy/hassio-addons/releases/latest/download/zeronsd-armv7.tar.gz
Reusing existing connection to github.com:443.

HTTP request sent, awaiting response... 
302 Found
Location: https://github.com/daoudeddy/hassio-addons/releases/download/v0.5.2/zeronsd-armv7.tar.gz [following]

--2022-05-31 11:43:13--  https://github.com/daoudeddy/hassio-addons/releases/download/v0.5.2/zeronsd-armv7.tar.gz

Reusing existing connection to github.com:443.

HTTP request sent, awaiting response... 
404 Not Found
2022-05-31 11:43:13 ERROR 404: Not Found.

Removing intermediate container ff014a637327

**Comment by daoudeddy** [comment]
Thank @gabrielribbae for reaching out.

Current solution is by reverting to version 0.4.3 since theres a cross compile build error. I need to contact the original ZeroNS devs to figure out the situation.

For now it should work as expected.

**Comment by daoudeddy** [comment]
Fixed
