### ISSUE TITLE
Error installing 

### ISSUE THREAD

**Issue by undulattice** [daoudeddy/hassio-addons#18]
Hi.

I'm trying to get this running in the latest version of Home Assistant (HassOS) and I'm getting the following error pop up:

> Failed to install add-on
The command '/bin/ash -o pipefail -c wget "https://github.com/daoudeddy/zerons-addon/releases/latest/download/zeronsd-${BUILD_ARCH}.tar.gz" -O zeronsd.tar.gz' returned a non-zero code: 8

Running:
HA 2023.1.5
HassOS 9.4

Any ideas how I can fix it?

Thanks

**Comment by daoudeddy** [comment]
I'm having a huge headache trying to cross compile this project to support multiple architectures with no success.

Edit: can you try now?

**Comment by undulattice** [comment]
Looks like it has installed successfully. :-)
Will try some config and see how I get on.

**Comment by undulattice** [comment]
Updated to latest version.
Installs perfectly, settings entered.

Fails to start. Log returns:


s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: ZeroNS
 ZeroNS is a name service centered around the ZeroTier Central API
-----------------------------------------------------------
 Add-on version: 20230120
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.4  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.1.5
 Home Assistant Supervisor: 2022.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[21:48:01] INFO: Configuring timezone (Europe/London)...
s6-rc: info: service base-addon-timezone successfully started
Log level is set to INFO
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/zerons.sh
/package/admin/s6-overlay-3.1.3.0/etc/s6-rc/scripts/cont-init: 20: /etc/cont-init.d/zerons.sh: Permission denied
cont-init: info: /etc/cont-init.d/zerons.sh exited 126
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-timezone: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-timezone successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by daoudeddy** [comment]
Fixed for now, can you update and try again?

**Comment by undulattice** [comment]
Looking better, but...

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: ZeroNS
 ZeroNS is a name service centered around the ZeroTier Central API
-----------------------------------------------------------
 Add-on version: 20230121
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.4  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.1.6
 Home Assistant Supervisor: 2022.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[10:03:15] INFO: Configuring timezone (Europe/London)...
s6-rc: info: service base-addon-timezone successfully started
Log level is set to INFO
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/zerons.sh
cont-init: info: /etc/cont-init.d/zerons.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun zerons (no readiness notification)
s6-rc: info: service legacy-services successfully started
zeronsd: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by zeronsd)
zeronsd: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by zeronsd)
zeronsd: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by zeronsd)
s6-svscanctl: fatal: unable to control /var/run/s6/services: No such file or directory



Last four lines repeat indefinitely.

**Comment by daoudeddy** [comment]
Can you try now?

**Comment by undulattice** [comment]
Sorted.
Thank you! :-)
